### ISSUE TITLE
Spacing between letters on the custom font is too large

### ISSUE THREAD

**Issue by Gutin1** [StarLegacy/StarLegacyResourcePack#22]
![image](https://user-images.githubusercontent.com/57606752/86674036-df0b3800-bfbd-11ea-93e2-64a6887fb12e.png)
![image](https://user-images.githubusercontent.com/57606752/86674057-e599af80-bfbd-11ea-8bcd-4a5a3bc09552.png)

**Comment by Peter-Crawley** [comment]
#25 fixes this, it's lazy but it works.

**Comment by MicleBrick** [comment]
Isn't this already fixed on the 1.16 branch?
